### PR TITLE
add discord bot with tabular responses

### PR DESCRIPTION
**Pull request by veerbia**
#50

### CODE REVIEW

**Comment by veerbia** [comment]
#52

**Comment by veerbia** [comment]
#52

**Review by asaprahul — APPROVED** [review]
sweet, that was fast. where will this be deployed? approving to unblock

**Comment by veerbia** [comment]
Prob Heroku but searching around in case anything more recommended for our use case

**Comment by veerbia** [comment]
Not letting me merge I think need to be added as org member for write access

**Pull request merged**
