### PR TITLE
mobile ui

### PR DESCRIPTION
**Pull request by noahvember**
📱

### CODE REVIEW

**Comment by asaprahul** [comment]
wow this is great. nice work @noahvember 

I think this is almost there. Some minor feedback before we can merge and ship this:

1. Thoughts on making the search bar more prominent?

Screenshot 2023-03-14 at 11 02 33 PM


2. This is pretty neat, but I'm afraid user might miss the SQL and data tables.

Screenshot 2023-03-14 at 11 04 37 PM

For example, on this screen it's hard to know what the actual query was and what was the data (table) output by the search.

Screenshot 2023-03-14 at 11 07 05 PM

One way we could achieve it is by using a bottom sheet. But I'm open to other ideas. Overall, I am a fan of the idea that on mobile the map / chart occupies 80% of the screen. It's a really special UX

**Comment by noahvember** [comment]
thanks, and good points!

1. will definitely make it wider, was also thinking about removing the clear button on mobile only. any other thoughts how? could also go taller and be more text area like

thinking the query could be shown in a closeable box above search bar after it is searched

2. bottom sheet would work, I was thinking it could be toggleable by an info icon button under the visual selectors?

**Comment by asaprahul** [comment]
1. For search bar, Perplexity does this really well on mobile. The just default to the "Go" button on the keyboard for search and "x" is subtle:



IMG_8235


2. Hmm, I'm not sure about the toggle. We can have it there in case users want that optionality. But what I understand so far from talking to users is the data (table) and SQL query is equally important in seeing what the actual values are (table) and how censusGPT came up with them (SQL query). But that's just from talking to users. What does your intuition say?

**Comment by noahvember** [comment]
That's a great search bar example

I was thinking of ways to view table and sql without the extra click: could make them appear as close able pop up boxes after a query, but this also involves mandatory close of mobile user doesn't care for it. Tricky because mobile is hard to display both visual or table/sql at the same time. Could also consider mobile users will not be same power users who want to view all data at once on a phone

Otherwise I was thinking to fly in the table and sql views above the search bar in closable boxes, user could manually close it or it can leave the page automatically after a timeout, while also leaving the icons to bring up after it's closed

**Comment by asaprahul** [comment]
Looks great @noahvember ! Thanks for adding this. 

Approving. Will merge soon (likely tomorrow AM) once a prod issue is fixed.

**Review by asaprahul — APPROVED** [review]

**Pull request merged**
