### PR TITLE
Fix string type casting - another 1

### PR DESCRIPTION
**Pull request by ananay**

### CODE REVIEW

**Comment by ananay** [comment]
image

**Review by asaprahul — CHANGES_REQUESTED** [review]
Screenshot 2023-03-13 at 10 47 11 PM


You will need to change line 44 too

**Comment by asaprahul** [comment]
Actually `.toString()` doesn't seem to work because Plotly just compresses the number in string :/ 

Screenshot 2023-03-13 at 10 50 08 PM

**Comment by asaprahul** [comment]
X-axis on Prod:
Screenshot 2023-03-14 at 12 25 05 AM

X-axis on proposed change:
Screenshot 2023-03-14 at 12 24 41 AM

(`backend response` in console log looks same between the two)

**Comment by ananay** [comment]
Should be good now @asaprahul

**Review by asaprahul — APPROVED** [review]
Looks good. nice @ananay

**Pull request merged**
